name: OpenCarwings
version: "0.0.20"
slug: opencarwings
description: Nissan CARWINGS-compatible server for bringing back Nissan TCUs and online services
url: https://github.com/Chaoscontrol/opencarwings-app
init: false
map:
  - ssl
arch:
  - amd64
ports:
  8124/tcp: 8124
  8125/tcp: 8125
  55230/tcp: 55230
ports_description:
  8124/tcp: Web UI and Navigator backend (HTTP)
  8125/tcp: Web UI (HTTPS)
  55230/tcp: Nissan TCU direct communication (TCU Link) - DO NOT CHANGE THIS PORT - IT IS FIXED BY THE TCU
options:
  timezone: UTC
  log_level: info
  trusted_domains: []
  ocm_api_key: ""
  iternio_api_key: ""
  monogoto_sms_delivery_webhook_enabled: false
schema:
  timezone: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  trusted_domains:
    - str?
  ocm_api_key: str?
  iternio_api_key: str?
  monogoto_sms_delivery_webhook_enabled: bool?
