serverAddr = "145.241.201.196"
serverPort = 7000
log.to = "/share/frp/frpc.log"

[[proxies]]
name = "ocw_tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 55230
remotePort = 55230
[proxies.metadatas]
auth = "token"
token = "oiV5xjReb^Hn"

[[proxies]]
name = "ocw_http"
type = "http"
localIP = "127.0.0.1"
localPort = 8124
customDomains = ["ocw-ha.duckdns.org"]
[proxies.metadatas]
auth = "token"
token = "oiV5xjReb^Hn"
